### ISSUE TITLE
Help installing the sophus dependecies

### ISSUE THREAD

**Issue by UnexpectedGinger** [songuke/dvo_slam#5]
I am following this github guide to installing dvo_slam on ros indigo ( https://github.com/songuke/dvo_slam ). I almost have it working, but every time i compile I get the following error:

/usr/bin/ld: /usr/local/lib/libg2o_core.a(hyper_graph_cpp.o): relocation R_X86_64_325 against '_ZTVN3g2o10HyperGraph4EdgeE' can not be used when making a shared object: recompile with -fPIC /usr/local/lib/libg2o_core.a: error adding symbols: Bad value collect2: error: ld returned 1 exit status

This error apparently is related to the dvo_slam/CMakeFiles/dvo_slam.dir/all file. I believe the error originated in the modified Sophus dependency folder, but I am unsure.

I also get the following CMake warning:

"(dev) at perception_pcl/pcl_ros/CMakeLists.txt:80 (add_dependencies): Policy CMP0046 is not set: Error on non-existent dependency in add_dependencies. Run "cmake -- help-policy CMP0046" for policy details. Use the cmake_policy command to set the policy and suppress this warning.

The dependency target "pcl_ros_generate_messages_cpp" of target "pcl_ros_tf" does not exist."

I believe that this warning does not impact the error, but I am unsure. I'm including it in case it does.

Any help on resolving these would be greatly appreciated, as the package compiles 98% of the way.

**Comment by songuke** [comment]
Hi,

From this error:
/usr/bin/ld: /usr/local/lib/libg2o_core.a(hyper_graph_cpp.o): relocation
R_X86_64_325 against '_ZTVN3g2o10HyperGraph4EdgeE' can not be used when
making a shared object: recompile with -fPIC /usr/local/lib/libg2o_core.a:
error adding symbols: Bad value collect2: error: ld returned 1 exit status

Perhaps check your g2o compilation and try recompiling it as a shared
library.

2017-02-20 12:37 GMT+08:00 UnexpectedGinger <notifications@github.com>:

**Comment by UnexpectedGinger** [comment]
I looked into g2o, but I realized this error was also appearing while I tried to build the Sophus library. 

" Failed to find Ceres - Missing required Ceres dependency: Eigen version 3.0.5, please set EIGEN_INCLUDE_DIR."

Furthermore, I get this error every time I try to compile any of the dvo files:
"CMake Error at dvo_core/CMakeLists.txt:8 (find_package):
  By not providing "FindEigen3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Eigen3", but
  CMake did not find one.

  Could not find a package configuration file provided by "Eigen3" with any
  of the following names:

    Eigen3Config.cmake
    eigen3-config.cmake

  Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
  "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
  provides a separate development package or SDK, be sure it has been
  installed."

**Comment by songuke** [comment]
Do you have Eigen and Ceres installed on your system?

And check if FindEigen3.cmake is available to your CMake.

Another thing is to check the version of the installed Eigen. I remember I
could only compile with Eigen <= 3.2. Please try.

2017-02-21 0:39 GMT+08:00 UnexpectedGinger <notifications@github.com>:

**Comment by UnexpectedGinger** [comment]
I went through my files as you suggested, and decided to attempt a clean re-install to fix the issues. I found this github repository: "https://github.com/jefftee/dvo_slam/tree/indigo-develop" and tried installing this. However, I get the error: 
/home/ros-industrial/dvo_slam/src/dvo_core/src/dense_tracking.cpp:346:50: error: ‘initial’ cannot be used as a function
         b = ls.b.cast<double>() + cfg.Mu * initial().log();
                                                    ^
  /home/ros-industrial/dvo_slam/src/dvo_core/src/dense_tracking.cpp:371:36: error: ‘estimate’ cannot be used as a function
     result.Transformation = estimate().inverse().matrix();

I don't understand what's going on. I figured I might be able to get somewhere if I downloaded this, tried using rosmake on the packages and keeping your suggestions in mind.
